### ISSUE TITLE
src files are missing 

### ISSUE THREAD

**Issue by aliess** [riscv-ovpsim/imperas-riscv-tests#10]
Hello guys,

I am trying to generate the tests from the test-suite, I can generate them for rv32i just fine, but any other extension would fail because the src folders are missing, I can see them in the initial commit but they're removed later on, any reason why? and is this repository maintained or are you maintaining another one for the test-suite?

**Comment by duncangraham-Imperas** [comment]
This repository provides the base ISA tests that can be executed with riscvOVPsim.
The riscvOVPsimPlus simulator, built upon the basics of riscvOVPsim, adds supports for trace capabilities and also 'near ratified' extensions such a Vector, Bit manipulation and Crypto (K) and can be obtained, along with the tests, by looking up the riscvOVPsimPlus links on the page https://www.ovpworld.org/riscvOVPsimPlus

**Comment by aliess** [comment]
Thank you, the package provided by ovpworld has all the tests.
