### ISSUE TITLE
Questions/issues with the testing...

### ISSUE THREAD

**Issue by ghost** [riscv-ovpsim/imperas-riscv-tests#13]
Performing a raw clone and simply typing `make` or `make all_variant` without doing anything else has numerous issues.  

I know the README.md specifies a specific methodology to set this up/run it, but I'm impatient.  :grin:  I expected all tests to be built, but I get makefile errors instead.

1. The Makefile recursively calls `make` with each invocation passing in the job control (-j8).  Suggest that you let the user define the job control on the command line (yes there is a PARALLEL flag to turn this off, but that's not documented).
   ```
    make
    for isa in rv32f rv32i rv32ic rv32m rv64d rv64f rv64i rv64ic rv64m; do \
    	make -j8 --max-load=4 RISCV_TARGET=riscvOVPsim RISCV_TARGET_FLAGS="" RISCV_DEVICE=$isa RISCV_ISA=$isa variant; \
    		rc=$?; \
    		if [ $rc -ne 0 ]; then \
    			exit $rc; \
    		fi \
    done
    make[1]: Entering directory '/home/knutel/work/imperas-riscv-tests'
    make -j8 --max-load=4 \
    	RISCV_TARGET=riscvOVPsim \
    	RISCV_DEVICE=rv32f \
    	RISCV_PREFIX=riscv64-unknown-elf- \
    	RISCV_ISA=rv32f \
    	run -C /home/knutel/work/imperas-riscv-tests/riscv-test-suite/rv32f
    make[2]: Entering directory '/home/knutel/work/imperas-riscv-tests'
    make[2]: warning: -j8 forced in submake: resetting jobserver mode.
   ```
2. `make` without env arguments actually does something, but it crashes:
    ```
    make -j8 --max-load=4 \
    	RISCV_TARGET=riscvOVPsim \
    	RISCV_DEVICE=rv32f \
    	RISCV_PREFIX=riscv64-unknown-elf- \
    	RISCV_ISA=rv32f \
    	run -C /home/knutel/work/imperas-riscv-tests/riscv-test-suite/rv32f
    make[2]: Entering directory '/home/knutel/work/imperas-riscv-tests'
    make[2]: warning: -j8 forced in submake: resetting jobserver mode.
    make[2]: *** No rule to make target 'run'.  Stop.
    ```
   Suggest error messaging telling the user they goofed.

1. `make clean simulate verify cover     RISCV_ISA=rv64i RISCV_DEVICE=rv64i` doesn't work.  Are these tests ready?  It seems that only the rv32i test has a Makefile

**Comment by ghost** [comment]
Just for clarity, this does work for me just fine...
```
make clean simulate verify cover     RISCV_ISA=rv32i RISCV_DEVICE=rv32i
```

**Comment by Imperas** [comment]
The github only has the rv32i tests included. All the other suites are released as opensource under OVPworld:  www.ovpworld.org/riscvOVPsimPlus

Thanx for the Issues with Make and env. We will investigate.

**Comment by UditPramod** [comment]
what are the steps to be followed for verifying a riscv processor using this platform.

**Comment by UditPramod** [comment]
How to use the .exe file given in the cloned folder for simulation

**Comment by Imperas** [comment]
> what are the steps to be followed for verifying a riscv processor using this platform.

This is an example of an Imperas compliance test suite and includes a free reference simulator that can be used for trace file comparison verification.

I suggest you search for videos and conference papers on CPU design verification.
For example, put this in google: 'riscv cpu verification riscvovpsim'
or google this 'riscv cpu verification riscvovpsim video'

The free Imperas riscvOVPsimPlus reference ISS is used by many groups to compare against their RTL. - Again I would suggest a search.

You could look at some of the Imperas videos on the subject. For example:
https://www.imperas.com/verifying-all-flexibility-risc-v-within-soc-dv-test-plans

Simon

**Comment by Imperas** [comment]
> How to use the .exe file given in the cloned folder for simulation

I would suggest you read the included documentation:
https://github.com/riscv-ovpsim/imperas-riscv-tests

**Comment by UditPramod** [comment]
Respected sir

I am doing my masters in VLSI at IIT Guwahati.  As part of my project I
require to verify a RISC-V processor that I designed. Is it possible to buy
a platform from Imperas for the same.

Regards
Udit Pramod
M.Tech VLSI
IIT GUWAHATI

**Comment by Imperas** [comment]
pls contact info@imperas.com
