### ISSUE TITLE
Does it currently support B extension?

### ISSUE THREAD

**Issue by mohanson** [riscv-ovpsim/imperas-riscv-tests#14]
I tried to compile a program with the tools provided by https://github.com/riscv/riscv-bitmanip and run it with riscvOVPsim, but got this message:

```
$ ./riscvOVPsim.exe --override riscvOVPsim/cpu/add_Extensions=B --variant RV64GCB --program main

Fatal (FP_NBE) This product does not support the Bit Manipulation extension. Other Imperas simulators and models fully support and implement the Bit Manipulation extension - please contact info@imperas.com for details
Info Exiting
```

Am I using it the right way? Or the b extension is not currently supported?

**Comment by duncangraham-Imperas** [comment]
riscvOVPsim supports the RISC-V Foundation's public User and Privilege specifications, including all standard and ratified extensions i.e. I E M A F D C S U N.
riscvOVPsimPlus extends the functionality of riscvOVPsim and provides many more features including full configurable instruction trace, GDB/Eclipse debug, and memory configuration options. Additionally in the model are: CLIC, Debug Module/Mode, multi-hart, H-hypervisor simulation, and also 'near-ratified' ISA extensions: V-vector, B-bitmanip, K-crypto(scalar).
See the [OVPWorld riscvOVPsimPlus](https://www.ovpworld.org/riscvOVPsimPlus) page and the link to the riscvOVPsimPlus library page for downloads.

**Comment by mohanson** [comment]
Thanks, you provided very detailed information, I understand what to do next.
