### ISSUE TITLE
Broken Download for riscvOVPsimPlus

### ISSUE THREAD

**Issue by fpedd** [riscv-ovpsim/imperas-riscv-tests#18]
I would like to download the riscvOVPsimPlus with vector ('v'-extension) support. I thus registered at www.ovpworld.org and tried to download the simulator from [here](https://www.ovpworld.org/library/wikka.php?wakka=riscvOVPsimPlus). However, when clicking the "download" button I simply get redirected to the forum where I am already logged in. What am I missing? Where can I download the riscvOVPsimPlus simulator?

**Comment by duncangraham-Imperas** [comment]
Please can you start from a fresh browser and perform the steps in the same page. 
1) log into the OVP Forum
2) Go to the riscvOVPsimPlus library page
3) download riscvOVPsim
I have done this to download riscvOVPsimPlus without issue

**Comment by fpedd** [comment]
Thanks. Clearing my browsing data fixed the issue!
