### ISSUE TITLE
Correct RISCV_TOOLCHAIN path for riscv-toolchains-rvv-0.9.x

### ISSUE THREAD

**Issue by superbchetan** [riscv-ovpsim/imperas-riscv-tests#28]
Hi There,

The README mention about setting up the following env vars, but riscv-toolchains-rvv-0.8.x and riscv-toolchains-rvv-0.9.x has different directory structures. If I want to use riscv-toolchains-rvv-0.9.x, what would be the correct values for RISCV_TUPLE, RISCV_PREFIX, RISCV_TOOLCHAIN?

```
# for vector rvv-0.8.x
RISCV_TUPLE=riscv64-unknown-elf
export RISCV_PREFIX=${RISCV_TUPLE}-
export RISCV_TOOLCHAIN=${TOPDIR}/riscv-toolchains-rvv-0.8.x/Linux64/sifive-riscv-none-gcc
export PATH=${PATH}:${RISCV_TOOLCHAIN}/bin
```

Thanks

**Comment by duncangraham-Imperas** [comment]
If you go to the repository for the toolchain you want to use or clone it you will see the information required to setup the toolchain in the README file. It is very simple. The RISCV_PREFIX is set to the first parts of the GCC name (without the gcc) and then the bin directory containing the GCC should be added to the PATH
